version: '3.8'

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db

  directus:
    extends:
      file: docker-compose.base.yml
      service: directus

  pgadmin:
    extends:
      file: docker-compose.base.yml
      service: pgadmin

  cinema-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    container_name: cinema-service-dev
    restart: always
    links:
      - db
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


volumes:
  cinema-app-db-data:
    driver: local
  pgadmin-data:
    driver: local
